### ISSUE TITLE
Доработать калькулятор

### ISSUE THREAD

**Issue by trv1** [ivanstiv/calculator#9]
Работаем с файлом calc4.rb. Делаем в новой ветке с созданием пулреквеста. Ветку называем issue-9.

1. Вынести в отдельную функцию содержимое ветки else, а именно строки 23-36. Затем там же в ветке else нужно вызывать эту функцию. После всех преобразований программа должна работать также, как и ранее.
2. В сценарии, когда пользователь вводит два числа со знаком, добавить ещё несколько операций: "%" – процент от числа (например 5 % 60 должно дать ответ 3), "^" – возведение в степень.

**Comment by ivanstiv** [comment]
close
